# pytest.ini
[pytest]
# Запускаем только модульные тесты библиотеки
testpaths =
    arca_langlib/tests

# Игнорируем старые/legacy тесты
norecursedirs =
    .git
    venv
    docs
    ci
    arca_core
    phases
    tests

