name: Arca CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests/

    - name: Run tests with coverage
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest --cov=arca_core --cov=arca_interpreter --cov=arca_memory tests/ > coverage.txt
        cat coverage.txt

    - name: Run schema tests
      run: |
        pytest tests/test_schema.py --cov=arca_fieldcore --cov-report=term

    - name: Run evaluator tests
      run: |
        pytest tests/test_evaluator.py --cov=arca_interpreter --cov-report=term
