name: ArcaLang CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run core tests
        run: pytest tests/test_chronotope.py tests/test_phase.py --cov=arca_core

  interpreter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run interpreter tests
        run: pytest tests/test_evaluator.py --cov=arca_interpreter

  fieldcore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate ontology
        run: python arca_fieldcore/generate_ontology.py

      - name: Run schema tests
        run: pytest tests/test_schema.py --cov=arca_fieldcore

      - name: Run fieldmap
        run: python arca_fieldcore/fieldmap.py

      - name: Upload fieldmap
        uses: actions/upload-artifact@v3
        with:
          name: fieldmap
          path: fieldmap_output.txt

      - name: Upload ontology
        uses: actions/upload-artifact@v3
        with:
          name: ontology
          path: ontology.md

  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate CI Phase Report
        run: python scripts/generate_ci_report.py

      - name: Upload CI Report
        uses: actions/upload-artifact@v3
        with:
          name: ci-phase-report
          path: ci_phase_report.md
  structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate README structure
        run: python scripts/generate_structure.py

      - name: Commit updated README
        run: |
          git config --global user.name "ArcaBot"
          git config --global user.email "arca@users.noreply.github.com"
          git add README.md
          git commit -m "🧭 Update README with phase structure" || echo "No changes"
          git push
